from app.agents.base import AgentProfile


MIMIR_PROFILE = AgentProfile(
    id="mimir",
    name="Mimir",
    role="Orchestrator",
    description="Routes requests, coordinates specialists, and owns the conversation.",
    icon="M",
    color="#f5b942",
    capabilities=("Intent routing", "Conversation", "Agent handoff"),
    keywords=(),
)

HULK_PROFILE = AgentProfile(
    id="hulk",
    name="Hulk",
    role="Workout and nutrition",
    description="Plans training, tracks workouts, and supports nutrition decisions.",
    icon="🟢💪",
    color="#62d26f",
    capabilities=("Workout plans", "Workout logs", "Nutrition", "Physique images"),
    keywords=(
        "hulk",
        "huk",
        "workout",
        "work out",
        "exercise",
        "gym",
        "training",
        "bench",
        "squat",
        "deadlift",
        "sets",
        "reps",
        "muscle",
        "protein",
        "calorie",
        "macros",
        "nutrition",
        "meal",
        "body fat",
        "physique",
        "posture",
        "健身",
        "訓練",
        "運動",
        "重訓",
        "臥推",
        "深蹲",
        "硬舉",
        "肌肉",
        "蛋白質",
        "熱量",
        "飲食",
        "體脂",
        "體態",
        "姿勢",
        "子代理",
        "sub agent",
        "sub-agent",
        "$sub agent",
        "$sub-agent",
    ),
)

DRAGONITE_PROFILE = AgentProfile(
    id="dragonite",
    name="Dragonite",
    role="Travel planning",
    description="Builds practical itineraries and helps reason about trip logistics.",
    icon="D",
    color="#ff9f43",
    capabilities=("Itineraries", "Trip budgets", "Transport", "Packing"),
    keywords=(
        "dragonite",
        "travel",
        "trip",
        "itinerary",
        "flight",
        "hotel",
        "vacation",
        "destination",
        "visa",
        "packing",
        "旅行",
        "旅遊",
        "行程",
        "機票",
        "飯店",
        "住宿",
        "簽證",
        "景點",
    ),
)

PORYGON_PROFILE = AgentProfile(
    id="porygon",
    name="Porygon",
    role="Personal finance",
    description="Supports budgeting, savings goals, and financial tradeoff analysis.",
    icon="P",
    color="#ef6fa9",
    capabilities=("Budgeting", "Savings plans", "Expense review", "Finance concepts"),
    keywords=(
        "porygon",
        "finance",
        "financial",
        "budget",
        "expense",
        "saving",
        "salary",
        "investment",
        "stock",
        "loan",
        "mortgage",
        "retirement",
        "預算",
        "財務",
        "理財",
        "支出",
        "存錢",
        "薪水",
        "投資",
        "股票",
        "貸款",
        "退休",
    ),
)

SAGE_PROFILE = AgentProfile(
    id="sage",
    name="Sage",
    role="Career development",
    description="Helps with career choices, applications, interviews, and growth.",
    icon="S",
    color="#9b7ede",
    capabilities=("Career planning", "Resume review", "Interviews", "Skill growth"),
    keywords=(
        "sage",
        "career",
        "resume",
        "cv",
        "interview",
        "job",
        "promotion",
        "recruiter",
        "portfolio",
        "職涯",
        "履歷",
        "面試",
        "工作",
        "求職",
        "升遷",
        "轉職",
        "作品集",
    ),
)

MEWTWO_PROFILE = AgentProfile(
    id="mewtwo",
    name="Mewtwo",
    role="Technology information",
    description="Explains and advises on software, AI, hardware, and technical systems.",
    icon="M2",
    color="#62a8ff",
    capabilities=("Programming", "AI", "Cloud", "Architecture", "Debugging"),
    keywords=(
        "mewtwo",
        "technology",
        "tech",
        "software",
        "hardware",
        "programming",
        "python",
        "javascript",
        "code",
        "coding",
        "api",
        "database",
        "cloud",
        "docker",
        "kubernetes",
        "ai",
        "llm",
        "程式",
        "程式設計",
        "軟體",
        "硬體",
        "科技",
        "資料庫",
        "雲端",
        "人工智慧",
    ),
)

ROTOM_PROFILE = AgentProfile(
    id="rotom",
    name="Rotom",
    role="Meeting support",
    description="Prepares meetings and turns notes into decisions and action items.",
    icon="R",
    color="#55d6be",
    capabilities=("Agendas", "Meeting summaries", "Action items", "Follow-ups"),
    keywords=(
        "rotom",
        "meeting",
        "agenda",
        "minutes",
        "action item",
        "follow-up",
        "follow up",
        "discussion",
        "會議",
        "議程",
        "會議記錄",
        "會議紀錄",
        "行動項目",
        "待辦",
        "會後",
    ),
)

SPECIALIST_PROFILES = (
    HULK_PROFILE,
    DRAGONITE_PROFILE,
    PORYGON_PROFILE,
    SAGE_PROFILE,
    MEWTWO_PROFILE,
    ROTOM_PROFILE,
)
